### PR TITLE
Add Cython Extension Example

### PR DESCRIPTION
**Pull request by SubtleMuffin**
This PR introduced a `Cython` extension example.

Steps are included in the `README.md`.

Test:
  - Manual test following `README.md`
  - GitLab CI/CD procedures need to be updated

### CODE REVIEW

**Comment by kouchy** [comment]
Thank you for this PR!

To my mind, the proposed PR misses some elements to be integrated in AFF3CT as is:
  - all the proposed examples are targeting a small working chain of a digital communication system, we would expect the same for the Cython example,
  - I don't see the Python calls part. Perhaps I missed something but we would expect a basic Python code using the new wrapped AFF3CT functions in Python,
  - all the proposed examples should be integrated in a pipeline of tests (I propose to do it if you want),
  - the AFF3CT workflow model is to accept PR in the `development` branch not in the `master` branch.

Could you modify your PR taking into account these previous points?

If you have any questions do not hesitate to ask them :-).

**Comment by SubtleMuffin** [comment]
Thank you for your advice. Please find my reply inline.

> Thank you for this PR!
> 
> To my mind, the proposed PR misses some elements to be integrated in AFF3CT as is:
> 
>     * all the proposed examples are targeting a small working chain of a digital communication system, we would expect the same for the Cython example,

Sure, a Polar encoder and decoder Cython wrapper is introduced.

>     * I don't see the Python calls part. Perhaps I missed something but we would expect a basic Python code using the new wrapped AFF3CT functions in Python,
> 

Sorry. Now, `polar_codec.py` is presented.

>     * all the proposed examples should be integrated in a pipeline of tests (I propose to do it if you want),
> 

I have some limited experience with Gitlab CI/CD. Possible steps in `.gitlab-ci.yml' could be
```yml
build_and_test:
  stage: build
  image: alpine:latest
  script:
    - apk add --update --no-cache alpine-sdk cmake python3
    - git submodule update --init --recursive
    - cd $CI_PROJECT_DIR/lib/aff3ct
    - mkdir build && cd build
    - cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-funroll-loops -march=native" -DAFF3CT_COMPILE_EXE="OFF" -DAFF3CT_COMPILE_STATIC_LIB="ON" -DAFF3CT_COMPILE_SHARED_LIB="ON"
    - make -j4
    - cd $CI_PROJECT_DIR/example/cython
    - mkdir -p cmake/Modules
    - cp ../../lib/aff3ct/build/lib/cmake/aff3ct-*/* cmake/Modules
    - mkdir build && cd build
    - cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-funroll-loops -march=native"
    - make
    - ./build/bin/my_project
    - cd $CI_PROJECT_DIR/example/cython
    - pip install cython
    - python setup.py build_ext -i
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../../lib/aff3ct/build/lib
    - python -c "import codec; print(codec.py_generate_frozen_bits(10, 16, 20))"
```


>     * the AFF3CT workflow model is to accept PR in the `development` branch not in the `master` branch.

Please note that, although I `rebase` to `development`, the dependencies are still with AFF3CT 2.3.4 (6cc383fa7), i.e., the same as `master`. The reason I did not bring it the same as `development` branch (ec40f26) is that the API seems to have changed a lot, e.g., the constructor for `Frozenbits_generator_GA` which I have no idea what is the [third argument](https://github.com/aff3ct/aff3ct/blob/ec40f269c4f2d7907bea23407615068206f96247/src/Tools/Code/Polar/Frozenbits_generator/Frozenbits_generator_GA.cpp#L24)... if possible, please help me on this... (a good doc on how to use them, and/or examples would be awesome!)

On a separate note, good job on refactoring the library (on dev branch), finally there is a `include` folder ;-)

> 
> Could you modify your PR taking into account these previous points?
> 
> If you have any questions do not hesitate to ask them :-).

**Comment by kouchy** [comment]
This is much more complete than the first PR, thanks!

As you can understand I would prefer to integrate your work to the up stream of the `development` branch.
Could you try to do this? If you agree, we will help you.
I would like to release the AFF3CT 2.4.0 version in the next months, it could be great to have your Cython example for polar codes working with this new version.
This is just a detail but, I think that you can change the name of your example from `cython` to `cython_polar` :-).

The parameters you don't understand in the GA method to generate the frozen bits can be ignored.
These two last parameters are here to dump the generated frozen bits in a file (see https://github.com/aff3ct/aff3ct/blob/development/src/Tools/Code/Polar/Frozenbits_generator/Frozenbits_generator.cpp#L78). We added this feature because some users asked us how to get the generated frozen bits when using the AFF3CT simulator (see https://aff3ct.readthedocs.io/en/latest/user/simulation/parameters/codec/polar/encoder.html#enc-fb-dump-path).

You're right, the AFF3CT API is not documented at this time. There is an important work to do that but we are currently discussing to start this documentation (like we did for the simulator).

One last point in prevision of the AFF3CT `v2.4.0`: for most of the library examples we propose a documentation (see https://aff3ct.readthedocs.io/en/latest/user/library/examples.html). I have some work to do to document the `sequence`, `sub-sequence` and `pipeline` examples and it could be great to have something similar for the `cython_polar` example. For the generation of the documentation we use `sphinx` combined to the `reStructuredText` language (this is something between `markdown` and `latex`). Here is the source file of the library examples doc: https://github.com/aff3ct/aff3ct/blob/development/doc/source/user/library/examples.rst.

**Comment by SubtleMuffin** [comment]
Thanks for your reply. Please see my further concerns below. I will go ahead close this PR, and generate a new one once I have fixed the compatibility issues I am having now.

> This is just a detail but, I think that you can change the name of your example from `cython` to `cython_polar` :-).

OK.

> The parameters you don't understand in the GA method to generate the frozen bits can be ignored.
> These two last parameters are here to dump the generated frozen bits in a file (see https://github.com/aff3ct/aff3ct/blob/development/src/Tools/Code/Polar/Frozenbits_generator/Frozenbits_generator.cpp#L78). We added this feature because some users asked us how to get the generated frozen bits when using the AFF3CT simulator (see https://aff3ct.readthedocs.io/en/latest/user/simulation/parameters/codec/polar/encoder.html#enc-fb-dump-path).

I still do not understand. The parameter I referred is `const Polar_code& code` of the **constructor** in the **derived** class `Frozenbits_generator_GA`, and cannot be ignored (viz. [here](https://github.com/aff3ct/aff3ct/blob/ec40f269c4f2d7907bea23407615068206f96247/src/Tools/Code/Polar/Frozenbits_generator/Frozenbits_generator_GA.cpp#L24)). The answers you have provided is the base class `Frozenbits_generator` and it has some pure virtual functions that blocks me from compiling (i.e., I cannot use the constructor of the class `Frozenbits_generator`.

> You're right, the AFF3CT API is not documented at this time. There is an important work to do that but we are currently discussing to start this documentation (like we did for the simulator).

Great! TBH, if possible, I would also want to see an `example` folder, which contains basic usages of *encoder*, *channel* *decoder* chain for every channel coding tools that AFF3CT provides, and some usages of utility/tool functions that may be used interchangeably in replacement of parts of the transceiver chain. For example, polar encoder, QPSK modulation, Rayleigh channel, QPSK demodulation, polar decoder chain, but we do not have to iterate all possibilities here, e.g., what if the channel is AWGN instead of Rayleigh.

> One last point in prevision of the AFF3CT `v2.4.0`: for most of the library examples we propose a documentation (see https://aff3ct.readthedocs.io/en/latest/user/library/examples.html). I have some work to do to document the `sequence`, `sub-sequence` and `pipeline` examples and it could be great to have something similar for the `cython_polar` example. For the generation of the documentation we use `sphinx` combined to the `reStructuredText` language (this is something between `markdown` and `latex`). Here is the source file of the library examples doc: https://github.com/aff3ct/aff3ct/blob/development/doc/source/user/library/examples.rst.

Do I need to create a PR there to improve the doc? Will it be in the `development` branch as well?

**Comment by SubtleMuffin** [comment]
For your information -- I personally find [these code review guidelines](https://google.github.io/eng-practices/review/) are very helpful.

**Comment by kouchy** [comment]
Oh, I see. We renamed the `Frozenbits_generator_GA` class in `Frozenbits_generator_GA_Arikan`. So you should use `Frozenbits_generator_GA_Arikan`. The `Frozenbits_generator_GA` class is the generic Gaussian Approximation for multi-kernel polar codes or for mono-kernels different from the initial 2x2 kernel proposed by Arikan. The `Polar_code` class has been introduced to characterize generic polar codes, but I think it is not relevant for you at this time and using the `Frozenbits_generator_GA_Arikan` class will solve your problem.

I see your point for the documentation of the API. Making more extensive examples will be a good improvement. However, there is a lot on features in AFF3CT and it will be a hard task... Did you check the `factory` example? (https://github.com/aff3ct/my_project_with_aff3ct/blob/development/examples/factory/src/main.cpp). It introduces high level component like the `codecs` that simplify the use of the modules. In the `factory` example it is possible to switch from channel code easily. It is also possible to use other modulation and so on. If you are not aware about this, I recommend you to check the doc.

The most advance and simple example to use is the `sequence` example, it enables to run the chain in parallel with a lot of flexibly. Today, I think this is the best way of using AFF3CT. But at this time there is no documentation about it...

Yes, to improve the doc, you need to create a PR in the AFF3CT repo and yes in the `development` branch as well.

Ok thanks, I will read these guidelines :-).

**Pull request closed without merging**
